name: Janitor
on:
  push:
    branches:
      - "develop"

jobs:
  branch:
    name: Find branch name
    runs-on: ubuntu-latest
    outputs:
      branchname: ${{ steps.branch.outputs.BRANCH_TO_DELETE }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Check if commit is merge commit
        id: branch
        run: ./.github/scripts/find-merge-source-branch.sh ${{ github.sha }}
  build:
    needs: branch
    name: Storage container cleanup
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: ["payex", "swedbankpay"]
    steps:
       # Set brand specific variables
      - name: Environment variables
        if: ${{ needs.branch.outputs.branchname }}
        id: variables
        run: ./.github/scripts/variables.sh --brand ${{ matrix.brand }} --ref ${{ github.ref }}

      - name: Azure Login
        if: ${{ needs.branch.outputs.branchname }}
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_STAGE }}

      - name: Delete feature folders
        if: ${{ needs.branch.outputs.branchname }}
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az storage blob delete-batch -s "\$web" --pattern ${{ needs.branch.outputs.branchname }}/** --account-name ${{ steps.variables.outputs.AZURE_ACCOUNT_STAGE }}