name: Janitor
on:
  push:
    branches:
      - "develop"

jobs:
  branch:
    name: Find branch name
    runs-on: ubuntu-latest
    outputs:
      branchname: ${{ steps.branch.outputs.BRANCH_TO_DELETE }}
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 0

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

      - name: Get branch name and delete merged feature branches
        id: branch
        run: ./.github/scripts/clean-merged-branches.sh
  build:
    needs: branch
    name: Storage container cleanup
    if: ${{ needs.branch.outputs.branchname }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: ["payex", "swedbankpay"]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
        with:
          fetch-depth: 2
        # Set brand specific variables
      - name: Environment variables
        id: variables
        run: ./.github/scripts/variables.sh --brand ${{ matrix.brand }} --ref ${{ github.ref }}

      - name: Azure Login
        uses: azure/login@4c03e4685fe81df2c50d5714c7d93cf39d8deb7f # @v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_STAGE }}

      - name: Delete feature folders
        uses: azure/CLI@bd09fd31a7fc217371c078f503fb6e264472c289 # v3
        with:
          inlineScript: |
            az storage blob delete-batch -s "\$web" --pattern ${{ needs.branch.outputs.branchname }}/** --account-name ${{ steps.variables.outputs.AZURE_ACCOUNT_STAGE }} --auth-mode login
        env:
          AZURE_CORE_USE_MSAL_HTTP_CACHE: false
