name: Main
on:
  push:
    branches:
      - "feature/**"
      - "develop"
      - "release/**"

jobs:
  build:
    name: Build and deploy
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: ["payex", "swedbankpay"]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      # Set brand specific variables
      - name: Environment variables
        id: variables
        run: ./.github/scripts/variables.sh --brand ${{ matrix.brand }} --ref ${{ github.ref }}

      - name: Set Node.js 18.x
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 18.x

      - name: Cache dependencies
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install
        run: npm ci

      - name: Build
        run: npm run ${{ steps.variables.outputs.BUILD_SCRIPT }} -- --env basename=${{ steps.variables.outputs.BRANCH }} --env semver=${{ steps.variables.outputs.BRANCH }} --env info_version=${{ steps.variables.outputs.VERSION }} --env github_actions=true

      - name: Create latest version reference file
        run: |
          echo "{ \"latestVersion\" : \"${{ steps.variables.outputs.BRANCH }}\" }" > ./dist/latestVersion.json

      - name: Azure Login
        uses: azure/login@4c03e4685fe81df2c50d5714c7d93cf39d8deb7f # @v3
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS_STAGE }}

      - name: Azure Deploy
        uses: azure/CLI@bd09fd31a7fc217371c078f503fb6e264472c289 # v3
        with:
          azcliversion: 2.43.0
          inlineScript: |
            az storage blob upload-batch -s dist -d \$web --account-name ${{ steps.variables.outputs.AZURE_ACCOUNT_STAGE }} --overwrite --auth-mode login
        env:
          AZURE_CORE_USE_MSAL_HTTP_CACHE: false
