name: Prepare release
on:
  push:
    branches:
      - "release/**"

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.variables.outputs.VERSION }}

    steps:
      - uses: actions/checkout@v2

      # Set brand specific variables
      - name: Environment variables
        id: variables
        run: ./.github/scripts/variables.sh --brand swedbankpay --ref ${{ github.ref }}

  changelog:
    runs-on: ubuntu-latest
    needs: version
    outputs:
      body: ${{ steps.pr-body.outputs.body }}

    steps:
      - uses: actions/checkout@v2
      - name: Update changelog
        id: changelog
        run: ./.github/scripts/update-changelog.sh ${{ needs.version.outputs.version }}

      # Content must be escaped to preserve newlines (https://github.community/t/set-output-truncates-multiline-strings/16852/3)
      - name: Get pull request body
        id: pr-body
        run: |
          body=$(cat RELEASE-NOTES.md)
          body="${body//'%'/'%25'}"
          body="${body//$'\n'/'%0A'}"
          body="${body//$'\r'/'%0D'}"
          echo ::set-output name=body::$body

  create-pr-master:
    runs-on: ubuntu-latest
    needs: [version, changelog]
    steps:
      - uses: actions/checkout@v2
      - name: Create pull requests
        uses: peter-evans/create-pull-request@v3
        with:
          base: master
          body: ${{ needs.changelog.outputs.body }}
          branch: ${{ github.ref }}
          title: Release ${{ needs.version.outputs.version }} (master)

  create-pr-develop:
    runs-on: ubuntu-latest
    needs: [version, changelog]
    steps:
      - uses: actions/checkout@v2
      - name: Create pull requests
        uses: peter-evans/create-pull-request@v3
        with:
          base: develop
          body: ${{ needs.changelog.outputs.body }}
          branch: ${{ github.ref }}
          title: Release ${{ needs.version.outputs.version }} (develop)
