name: Pull request
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        brand: ["payex", "swedbankpay"]
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6

      # Set brand specific variables
      - name: Environment variables
        id: variables
        run: ./.github/scripts/variables.sh --brand ${{ matrix.brand }} --ref ${{ github.ref }}

      - name: Set Node.js 18.x
        uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6
        with:
          node-version: 18.x

      - name: Cache dependencies
        uses: actions/cache@caa296126883cff596d87d8935842f9db880ef25 # v5
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Lint
        run: npm run lint
        continue-on-error: true # Allow linting errors to not fail the build, since after having re-enabled ESlint there's too many errors to be fixed before continuing on dev work

      - name: Test coverage
        run: npm run test:coverage

      - uses: codecov/codecov-action@f2274c2c340e0c81c8f7dc407b2a477b8935f171 # v6
        # with:
        #   files: ./coverage/lcov.info
        # fail_ci_if_error: true

      - uses: preactjs/compressed-size-action@261e5e2bb5332e35c78914ce69b4edcdf30da2ed # v3
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
          build-script: "${{ steps.variables.outputs.BUILD_SCRIPT }}"
          exclude: "{**/*.map,**/node_modules/**,**/*chunk*.*}"
          pattern: "{dist/**/*.js,dist/**/*.css}"
          # a file with a delta of less than 100 bytes will be reported as unchanged. [THN]
          minimum-change-threshold: 100
